trigger:
- master

pr: none

variables:

  # Azure Resource Manager connection
  azureSubscription: 'ci_cd_monster'

  # Resource group
  resourceGroupName: 'Deyvid-test'

  # Azure DevOps deployment environment
  environmentName: 'ci-cd-monster'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Docker Hub service connection name (set up in Project Settings → Service Connections)
  dockerHubConnection: 'dockerhub_service_connection'

  # Your Docker Hub username
  dockerHubNamespace: 'deyvidory'

  # Docker image name
  imageName: 'flatris'

  # Azure Container App name
  containerAppName: 'flatris-env'

  # Azure Container Apps Environment name
  containerAppsEnvironment: 'managedEnvironment-Deyvidtest-9357'

stages:
- stage: Test
  displayName: Test stage
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UseNode@1
      inputs:
        version: '18.x'
      displayName: 'Install Node.js'

    - script: yarn install
      displayName: 'yarn install'
      env:
        NODE_OPTIONS: --openssl-legacy-provider

    - script: yarn test
      displayName: 'Flow + Lint + Jest'
      env:
        NODE_OPTIONS: --openssl-legacy-provider

- stage: Build
  displayName: Build stage
  dependsOn: Test
  condition: succeeded()
  jobs:
  - job: Build
    displayName: Build Docker Image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: '$(dockerHubNamespace)/$(imageName)'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: 'Push to Docker Hub'
      inputs:
        command: push
        containerRegistry: '$(dockerHubConnection)'
        repository: '$(dockerHubNamespace)/$(imageName)'
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy to Container Apps
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - task: AzureContainerApps@1
            displayName: 'Deploy to Azure Container Apps'
            inputs:
              azureSubscription: '$(azureSubscription)'
              containerAppName: '$(containerAppName)'
              resourceGroup: '$(resourceGroupName)'
              containerAppsEnvironment: '$(containerAppsEnvironment)'
              imageToDeploy: '$(dockerHubNamespace)/$(imageName):$(Build.BuildId)'
              targetPort: '3000'
              ingress: 'external'
